name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true #使用resnet18预训练模型，加快训练收敛速度
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer: #优化器选择、学习率设置
  type: Adam #优化方法
  args:
    lr: 0.001 #学习率步长
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR #权重衰减
  args:
    warmup_epoch: 3
trainer: 
  seed: 2
  epochs: 12 #训练次数
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: '' #中断之前的训练，这里写上重新训练的文件名
  finetune_checkpoint: '' #微调已经训练好的模型
  output_dir: output
  tensorboard: false
dataset:
  train:
    dataset:
      args:
        data_path:
          - ./datasets/train.txt #训练集位置
        img_mode: RGB
    loader:
      batch_size: 8 #bacth_size 设置不能过大也不能过小
      shuffle: true #是否打乱数据集加载顺序，有利于模型训练的准确性
      pin_memory: true #内存较大时使用，DBNet进行了多次数据增强变换操作，有利于加快训练速度
      num_workers: 8 #加载数据的线程数
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - ./datasets/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 6
      collate_fn: ICDARCollectFN
